name: smoke test with GTFS dataset

on:
  workflow_call:
    inputs:
      feed-name:
        required: true
        type: string
      feed-download-cmd:
        required: true
        type: string
      feed-extract-cmd:
        required: true
        type: string
      feed-import-glob:
        required: true
        type: string
      feed-import-flags:
        required: true
        type: string

jobs:
  smoke-test:
    name: run ${{ inputs.feed-name }} smoke test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '22.x'
    - name: install sponge (moreutils)
      run: sudo apt install -y moreutils

    - name: install QSV
      run: ./ci/install-qsv.sh
    - name: enable QSV for file extensions other than .qsv
      run: |
        echo 'QSV_SKIP_FORMAT_CHECK=true' >>$GITHUB_ENV
    - name: install DuckDB
      run: |
        set -eux -o pipefail
        curl -fsSL -U '${{ github.repository }} CI' 'https://install.duckdb.org' | sh
        echo "$HOME/.duckdb/cli/latest" >>"$GITHUB_PATH"
        ~/.duckdb/cli/latest/duckdb --version

    - run: npm install

    - name: import ${{ inputs.feed-name }} GTFS
      run: |
        set -e
        set -o pipefail
        set -x

        db_name="${{ inputs.feed-name }}"

        # download & extract GTFS
        ${{ inputs.feed-download-cmd }}
        ${{ inputs.feed-extract-cmd }}

        # import GTFS
        ./cli.js -d ${{ inputs.feed-import-flags }} -- \
          "$db_name" \
          ${{ inputs.feed-import-glob }}
        # test if data has been imported
        duckdb -readonly -csv -c 'SELECT * FROM service_days LIMIT 1' "$db_name" | wc -l

        # delete database
        rm "$db_name"
